@host=http://localhost:8080/

###

POST {{host}}login HTTP/1.1

{
    "username": "test",
    "password": "test"
}

###

POST {{host}}login HTTP/1.1

{
    "username": "user1",
    "password": "password123"
}
