@host=http://localhost:8080/

###


POST {{host}}login HTTP/1.1

{
    "username": "user1",
    "password": "password123"
}

###

@token=user1:1732262339796421388

###

POST {{host}}crud/ HTTP/1.1
Authorization: Bearer {{token}}

{
    "email": "test@test.com",
    "name": "test test"
}
